# -*- coding: utf-8 -*-
"""LVADSUSR197_vishal_kokkula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X7GwVzAedoaRkc4uGzEIUhSYIq0l-EKI
"""

# 1

n = int(input("Enter no. of properties: "))
c_property = []

for i in range(n):

  prop = input("Enter the property Name (mall/office): ")
  length = float(input("Enter 'Length' of the property: "))
  width = float(input("Enter 'Width' of the property: "))
  area = length * width
  c_property.append((prop,area))

for i in range(len(c_property)):
  max_val = 0
  if c_property[i][1] > max_val:
    max_val = c_property[i][1]
  print(c_property[i][0],max_val)

# 2

weight = float(input("Enter Weight(in kgs): "))
height = float(input("Enter Height(in mts): "))
bmi = weight / (height ** 2)
print(bmi)

if bmi <= 10:
  print("Malnutrition, Eat good protein and go to gym")
elif bmi <= 25:
  print("Maintain the same!!")
else:
  print("Obese! Go join the gym now.")

# 3

n = int(input("Enter no. of students: "))
dict2 ={}
l_vals = []
for i in range(n):
  key = input("Enter the key(studentID): ")
  while True:
    vals = tuple(map(int,input("Enter the Marks(skip to go to the next student): ")))
    if not vals:
      break
    l_vals.append((vals))
print(l_vals)

# 4
age = int(input("Enter your age: "))

if age <= 12:
  print("recommend 'Children Collection' movies/TV shows")
elif age <= 19:
  print("recommend 'Teen Collection' movies/TV shows")
elif age <= 40:
  print("recommend 'Adult Collection' movies/TV shows")
else:
  print("recommend 'Senior Collection' movies/TV shows")

# 5

sub_ids = [1,2,3,4,5,6,7,8,9,10]
evn_sub_list =[]
for i in range(len(sub_ids)):
  if i%2 ==0:
    evn_sub_list.append(sub_ids[i])
print(evn_sub_list)

# 6

stored_security = "DSAI-LVA"

while True:
  password = input("Enter the password (Note: Skip to go back!!): ")
  if stored_security == password:
    print("You are now logged in")
    break
  else:
    print("Wrong Password! Try again.")
  if not password:
    break

# 7

# 8

def count_vowel(comments,vowels):
  count = 0
  for i in comments:
    if i[:] in vowels[:]:
      count = count+1
    return count



comments = ['hi','awesome','good','nyc']
vowels = ['a','e','i','o','u']
x = count_vowel(comments,vowels)
print(x)

# 9

# datetime module isnt discussed yet!

# 10

# 11
data = []
while True:
  polling = input("Enter the Poll (Yes/No) {skip to go back}: ").lower()
  req_format = ['yes','no']

  if polling in req_format:
    data.append(polling)
  else:
    print("wrong format")
  if not polling:
    break

print(data)

# 12

x = float(input("divisor: "))
y = float(input("divident: "))
if y <= 0:
  print("error! can't divide with 0")
else:
  print(x/y)

#15

script = []
news = input()
stocks =input()
performance = input()
industry_news = input()

script.append(news)
script.append(stocks)

